project:
  type: book
  output-dir: docs

book:
  title: "SF Data Tips and Tricks"
  author: "OEWD Data and Performance Team"
  date: "4/3/2024"
  chapters:
    - index.qmd
    - datasf.qmd
    - excel.qmd
    - sharepoint.qmd
    - spatial.qmd
    - geocoding.qmd
    - icons.qmd
    - snowflake.qmd
    - targets.qmd
    - references.qmd

bibliography: references.bib

format:
  oewd-report-html: default
  pdf:
    documentclass: scrreprt



